---

jobs:
  build:
    name: build / ${{ matrix.microservice }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          cache: npm
          node-version: 22

      - name: Install dependencies
        run: npm clean-install

      - name: Build ${{ matrix.microservice }} microservice
        run: npx lerna run build --scope @payap/${{ matrix.microservice }}
    strategy:
      matrix:
        microservice: [transactions, users, wallets]
  dependency-review:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/dependency-review-action@v4

name: CI

'on':
  push:
    branches: [ main ]
